### ISSUE TITLE
ImportError when a script is executable

### ISSUE THREAD

**Issue by DSamuylov** [vmorariu/figtree#4]
Dear @vmorariu and @gadomski,

I have a new issue, and I would highly appreciate if you could help me to solve it. I am getting an import error in the following case:

```
$ ls
test_figtree.py
$ cat test_figtree.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import figtree

print "Hi, figtree!"
$ chmod +x test_figtree.py
$ python test_figtree.py 
Hi, figtree!
$ ./test_figtree.py 
Traceback (most recent call last):
  File "./test_figtree.py", line 4, in <module>
    import figtree
ImportError: dlopen(/Users/denis/Documents/code/python/figtree/python/figtree.so, 2): Library not loaded: @rpath/libfigtree.dylib
  Referenced from: /Users/denis/Documents/code/python/figtree/python/figtree.so
  Reason: image not found
```

I installed figtree with `python setup.py build_ext --inplace` and exporting the following variables:

```
# figtree
export FIGTREE_DIR="/Users/denis/Documents/code/python/figtree"
export PYTHONPATH="${PYTHONPATH}:${FIGTREE_DIR}/python"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${FIGTREE_DIR}/lib"
```

For the second one with `python setup.py install` figtree always fails to be imported...

**Comment by gadomski** [comment]
I see a mix of `.so` and `.dylib` extensions, which tells me something is fishy. AFAICT, I didn't hardcode any library extensions [in my `cmakeify` branch](https://github.com/vmorariu/figtree/compare/master...gadomski:cmakeify).

@DSamuylov what system are you building on? Ubuntu or OSX?

Also, at your discretion this conversation might belong over on gadomski/figtree, since my CMake changes haven't been merged into vmorariu/figtree.

**Comment by DSamuylov** [comment]
@gadomski, thank you for your very prompt reply! I thought I used your `cmakeify` branch. Otherwise, I couldn't install it on OSX that was my previous issue... I am rebuilding it to be sure.

**Comment by gadomski** [comment]
Ah, after some reading I've learned that Python uses an `.so` extension even on OSX. So disregard that idea.

However, if you're on OSX you'll probably want `DYLD_LIBRARY_PATH` instead of `LD_LIBRARY_PATH`. Try changing that — if you continue to get failures, I'll try to replicate locally and then tweak the rpath junk...rpath is always messy...

**Comment by vmorariu** [comment]
I agree with gadomski that there is something fishy going on with the 
extensions. It looks like the .so extension is for the python module 
created by the "python setup.py build_ext --inplace" command.  But, the 
setup.py script does not add the .so extension either, and it seems that 
gadomski's CMake is correctly adding the .dylib extension to the C 
library. Maybe cython is adding the .so extension?

Anyway, the fact that the script works when the it is provided to python 
as an argument makes me think it's not the extension that is the problem 
here, but rather that it is a library path problem. The C library 
libfigtree.dylib a dependency of the python module figtree.so, and it is 
not found when the script is executed directly. Maybe some paths are set 
slightly differently depending on how python is invoked (directly w/ the 
script as argument, or indirectly via "#!/usr/bin/env python").

**Comment by DSamuylov** [comment]
@vmorariu and @gadomski, thank you a lot for your replies... With all meetings, I just finished rebuilding figtree from cmakeify branch and it solved the problem! Thank you a lot for your help!
